version: "1"

services:
  write_api:
    build: ./write_api
    ports:
      - "10003:10003"
    container_name: write_api

  read_api:
    build: ./read_api
    ports:
      - "10002:10002"
    container_name: read_api

  consumer_checksum:
    build: ./consumer/checksum
    container_name: consumer_checksum

  consumer_delete_event:
    build: ./consumer/delete_event
    container_name: consumer_delete_event
  
  consumer_post_event:
    build: ./consumer/post_event
    container_name: consumer_post_event
  
  mysql:
    image: mysql/mysql-server:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: hello
    ports: 
      - "3306:3306"

  redis:
    image: redis:alpine

  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
    ports: 
      - "2122:2122"
      - "8030:3080"
      - "8032:8032"
      - "8040:8040"
      - "8088:8088"
      - "19888:19888"
      - "49707:49707"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "9000:9000"

  nsq:
    