FROM golang:1.11-alpine

RUN mkdir -p /go/src/github.com/g10guang/graduation/consumer/post_event
COPY ./write_api /go/src/github.com/g10guang/graduation/consumer/post_event

FROM alpine:3.7

EXPOSE 10002

WORKDIR /go/src/github.com/g10guang/graduation/consumer/post_event

CMD ["./post_event"]