FROM golang:1.11-alpine

RUN mkdir -p /go/src/github.com/g10guang/graduation/consumer/delete_event
COPY ./write_api /go/src/github.com/g10guang/graduation/consumer/delete_event

FROM alpine:3.7

EXPOSE 10002

WORKDIR /go/src/github.com/g10guang/graduation/consumer/delete_event

ENV PATH="${PATH}:/go/src/github.com/g10guang/graduation/consumer/delete_event"

CMD delete_event